/**
 * Validador de emails para prevenir dominios desechables/temporales
 *
 * Lista actualizada de dominios comunes usados para emails falsos
 */

// Dominios de email desechables/temporales más comunes
const DISPOSABLE_DOMAINS = new Set([
  // Servicios populares de email temporal
  '10minutemail.com',
  '10minutemail.net',
  'tempmail.com',
  'temp-mail.org',
  'tempmail.net',
  'throwaway.email',
  'throwawaymail.com',
  'guerrillamail.com',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'sharklasers.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailinater.com',
  'maildrop.cc',
  'getairmail.com',
  'fakeinbox.com',
  'fakemailgenerator.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'dispostable.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.me',
  'trashemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'mytrashmail.com',
  'mailexpire.com',
  'mailcatch.com',
  'mailnesia.com',
  'mailnull.com',
  'e4ward.com',
  'spamex.com',
  'spam4.me',
  'nwytg.net',
  'binkmail.com',
  'safetymail.info',
  'spamobox.com',
  'mintemail.com',
  'tempinbox.com',
  'emailondeck.com',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'anonymbox.com',
  'burnermail.io',
  'discard.email',
  'discardmail.com',
  'disposableaddress.com',
  'disposableemailaddresses.com',
  'disposableinbox.com',
  'emailsensei.com',
  'fakemailgenerator.net',
  'getnada.com',
  'grr.la',
  'hmamail.com',
  'inboxalias.com',
  'mailcatch.com',
  'mailchop.com',
  'maildx.com',
  'mailforspam.com',
  'mailfree.ga',
  'mailhazard.com',
  'mailhazard.us',
  'mailme24.com',
  'mailnator.com',
  'mailsac.com',
  'mailslite.com',
  'mailtemp.net',
  'mohmal.com',
  'mt2009.com',
  'mt2014.com',
  'mx0.wwwnew.eu',
  'nada.email',
  'nomail.xl.cx',
  'objectmail.com',
  'one-time.email',
  'otherinbox.com',
  'ourklips.com',
  'owlpic.com',
  'pjjkp.com',
  'pokemail.net',
  'proxymail.eu',
  'rcpt.at',
  'reallymymail.com',
  'recode.me',
  'receiveee.com',
  'recursor.net',
  'regbypass.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  's0ny.net',
  'safe-mail.net',
  'sdf.org',
  'sharedmailbox.org',
  'sharklasers.com',
  'shieldedmail.com',
  'shitmail.me',
  'shortmail.net',
  'shut.ws',
  'sinnlos-mail.de',
  'siteposter.net',
  'slapsfromlastnight.com',
  'slaskpost.se',
  'slopsbox.com',
  'smellfear.com',
  'smellrear.com',
  'snakemail.com',
  'sneakemail.com',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soisz.com',
  'solvemail.info',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.net',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spameater.com',
  'spameater.org',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spamlot.net',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'squizzy.de',
  'ssoia.com',
  'startkeys.com',
  'stinkefinger.net',
  'stop-my-spam.com',
  'stuffmail.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'tafmail.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.co',
  'tempmail.de',
  'tempmail.eu',
  'tempmail.it',
  'tempmail.net',
  'tempmail.us',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempmailaddress.com',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thecloudindex.com',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'throam.com',
  'throwawayemailaddress.com',
  'tilien.com',
  'tittbit.in',
  'tmailinator.com',
  'toiea.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trickmail.net',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'valemail.net',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'viralplays.com',
  'vkcode.ru',
  'vpn.st',
  'vsimcard.com',
  'vomoto.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'webm4il.info',
  'webtrip.ch',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whopy.com',
  'whtjddn.33mail.com',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wolfsmail.tk',
  'wollan.info',
  'worldspace.link',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.co',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yomail.info',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yourdomain.com',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.com',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
  'zxcv.com',
  'zxcvbnm.com',
  'zzz.com',
])

// Patrones sospechosos en dominios
const SUSPICIOUS_PATTERNS = [
  /^temp/i,
  /^fake/i,
  /^trash/i,
  /^spam/i,
  /^disposable/i,
  /^throwaway/i,
  /^mailinator/i,
  /^guerrilla/i,
  /10.*min/i,
  /minute.*mail/i,
]

export interface EmailValidationResult {
  isValid: boolean
  error?: string
}

/**
 * Valida si un email es de un dominio desechable/temporal
 */
export function validateEmail(email: string): EmailValidationResult {
  if (!email || typeof email !== 'string') {
    return { isValid: false, error: 'Correo electrónico inválido' }
  }

  const emailLower = email.toLowerCase().trim()

  // Validar formato básico
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(emailLower)) {
    return { isValid: false, error: 'Formato de correo electrónico inválido' }
  }

  // Extraer dominio
  const domain = emailLower.split('@')[1]

  if (!domain) {
    return { isValid: false, error: 'Dominio de correo inválido' }
  }

  // Verificar contra lista de dominios desechables
  if (DISPOSABLE_DOMAINS.has(domain)) {
    return {
      isValid: false,
      error: 'No permitimos correos temporales o desechables. Por favor usa un correo real.',
    }
  }

  // Verificar patrones sospechosos en el dominio
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(domain)) {
      return {
        isValid: false,
        error: 'Este dominio de correo no está permitido. Por favor usa un correo real.',
      }
    }
  }

  return { isValid: true }
}

/**
 * Lista de dominios válidos comunes (opcional, para modo estricto)
 * Descomenta si quieres solo permitir ciertos dominios
 */
// const ALLOWED_DOMAINS = new Set([
//   'gmail.com',
//   'googlemail.com',
//   'outlook.com',
//   'hotmail.com',
//   'live.com',
//   'yahoo.com',
//   'icloud.com',
//   'protonmail.com',
//   'proton.me',
//   // Dominios de Honduras
//   'unah.edu.hn',
//   'unitec.edu',
//   // etc.
// ])
