import type { NewLogro } from '@/db/schema'

/**
 * Configuración de logros del sistema
 * Define todos los logros disponibles con sus valores objetivo
 */
export const ACHIEVEMENTS_CONFIG: Omit<NewLogro, 'id' | 'creadoEn'>[] = [
  // Logros de validaciones totales (10 Logros principales)
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 1,
    nombre: 'El Primer Vistazo',
    descripcion: 'Valida tu primera acta e inicia la participación.',
    icono: '👁️',
    orden: 1,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 10,
    nombre: 'Doble Dígito',
    descripcion: 'Supera las 10 validaciones iniciales.',
    icono: '🔟',
    orden: 2,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 50,
    nombre: 'Comprometido',
    descripcion: '50 validaciones completadas. Compromiso demostrado.',
    icono: '✅',
    orden: 3,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 100,
    nombre: 'Maestro del Escrutinio',
    descripcion: '100 actas validadas. Enfoque de alta precisión.',
    icono: '🔪',
    orden: 4,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 250,
    nombre: 'La Vara de Medir',
    descripcion: '250 validaciones. Establece el estándar de calidad.',
    icono: '📐',
    orden: 5,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 500,
    nombre: 'Haciendo Historia',
    descripcion: '¡500 actas! Dejas una marca ineludible.',
    icono: '📜',
    orden: 6,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 750,
    nombre: 'Héroe de las Actas',
    descripcion: 'Valida 750 actas y salva el conteo.',
    icono: '🦸',
    orden: 7,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 1000,
    nombre: 'Inmortal del Conteo',
    descripcion: '1,000 actas. Tu leyenda en el sistema es permanente.',
    icono: '🛡️',
    orden: 8,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 1500,
    nombre: 'Semidiós del Voto',
    descripcion: '7,500 actas. Un paso de la deidad.',
    icono: '✨',
    orden: 9,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 2500,
    nombre: 'Dios del escrutinio',
    descripcion: '2,500 actas, dedicación divina.',
    icono: '👼',
    orden: 10,
  },

  // Logros de racha en sesión (Nombres divertidos, iconos únicos)
  {
    tipo: 'racha_sesion',
    valorObjetivo: 10,
    nombre: 'Café Cargado',
    descripcion: '10 actas sin levantarte. ¡El café está haciendo efecto!',
    icono: '☕',
    orden: 11,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 20,
    nombre: 'El Filtro Automático',
    descripcion: '20 validaciones seguidas. Mente en modo "piloto automático".',
    icono: '🤖',
    orden: 12,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 30,
    nombre: 'El Flujo del Escrutinio',
    descripcion: '¡30! Estás en la zona donde el tiempo se detiene.',
    icono: '🧘',
    orden: 13,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 40,
    nombre: 'Visión Láser',
    descripcion: '40 actas sin pestañear. ¡Más rápido que el internet!',
    icono: '💥',
    orden: 14,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 50,
    nombre: 'La Máquina del Tipeo',
    descripcion: '50 actas seguidas. ¡Eres más rápido que el CNE!',
    icono: '⌨️',
    orden: 15,
  },

  // Logros de reportes (Iconos únicos, orden reajustado)
  {
    tipo: 'reportes_totales',
    valorObjetivo: 5,
    nombre: 'Vigilante',
    descripcion: 'Reporta 5 problemas de datos.',
    icono: '🚨', // Nuevo icono
    orden: 16, // Ajustado
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 10,
    nombre: 'Protector',
    descripcion: 'Reporta 10 problemas con éxito.',
    icono: '👑', // Nuevo icono
    orden: 17, // Ajustado
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 20,
    nombre: 'Guardián',
    descripcion: 'Reporta 20 errores. Proteges la base de datos.',
    icono: '🔑', // Nuevo icono
    orden: 18, // Ajustado
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 25,
    nombre: 'Defensor',
    descripcion: 'Reporta 25 problemas. Defiendes la integridad cívica.',
    icono: '🎖️', // Nuevo icono
    orden: 19, // Ajustado
  },

  // Continuación: nuevos logros de racha (crecen +20 luego +25)
  {
    tipo: 'racha_sesion',
    valorObjetivo: 70,
    nombre: 'Turbo Humano',
    descripcion: '70 actas consecutivas. Estás más allá de la eficiencia.',
    icono: '⚡',
    orden: 20,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 90,
    nombre: 'Ritmo Inquebrantable',
    descripcion: '90 validaciones al hilo. No hay quien te detenga.',
    icono: '🔥',
    orden: 21,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 110,
    nombre: 'El Analista Imparable',
    descripcion: '110 actas sin pausa. Dominio absoluto.',
    icono: '🏎️',
    orden: 22,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 130,
    nombre: 'Trance Estadístico',
    descripcion: '130 validaciones seguidas. Mente y máquina alineadas.',
    icono: '🧠',
    orden: 23,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 150,
    nombre: 'Modo Leyenda',
    descripcion: '150 actas seguidas. Estás rompiendo números.',
    icono: '🌩️',
    orden: 24,
  },

  // Ahora incrementos de 25 hasta llegar a 500
  {
    tipo: 'racha_sesion',
    valorObjetivo: 175,
    nombre: 'Ritmo Celestial',
    descripcion: '175 validaciones sin detenerte. Ritmo divino.',
    icono: '☄️',
    orden: 25,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 200,
    nombre: 'La Muralla',
    descripcion: '200 validaciones consecutivas. Nada te mueve.',
    icono: '🧱',
    orden: 26,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 225,
    nombre: 'Ojo Eterno',
    descripcion: '225 validaciones al hilo. Ya no parpadeas.',
    icono: '👁️‍🗨️',
    orden: 27,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 250,
    nombre: 'Alineación Perfecta',
    descripcion: '250 validaciones seguidas. Un ejemplo de foco total.',
    icono: '🎯',
    orden: 28,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 275,
    nombre: 'Hiperconcentrado',
    descripcion: '275 validaciones. La precisión es tu naturaleza.',
    icono: '🧬',
    orden: 29,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 300,
    nombre: 'Máquina Viviente',
    descripcion: '300 validaciones sin parar. Eres una unidad de análisis.',
    icono: '⚙️',
    orden: 30,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 325,
    nombre: 'Constancia Titanica',
    descripcion: '325 validaciones seguidas. Fortaleza absoluta.',
    icono: '🏋️',
    orden: 31,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 350,
    nombre: 'Filtro Universal',
    descripcion: '350 validaciones. Lo detectas TODO.',
    icono: '🌐',
    orden: 32,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 375,
    nombre: 'Pulso Perfecto',
    descripcion: '375 validaciones consecutivas. Precisión rítmica.',
    icono: '🎵',
    orden: 33,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 400,
    nombre: 'Operador Supremo',
    descripcion: '400 validaciones sin fallar. Eficiencia máxima.',
    icono: '🛠️',
    orden: 34,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 425,
    nombre: 'Observador Omnisciente',
    descripcion: '425 validaciones. Nada escapa a tu vista.',
    icono: '🔭',
    orden: 35,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 450,
    nombre: 'El Juez del Dato',
    descripcion: '450 validaciones seguidas. Dictas precisión.',
    icono: '⚖️',
    orden: 36,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 475,
    nombre: 'Faro de Exactitud',
    descripcion: '475 validaciones seguidas. Eres una guía del conteo.',
    icono: '🗼',
    orden: 37,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 500,
    nombre: 'Infinito Operacional',
    descripcion: '500 validaciones seguidas. Haz alcanzado lo imposible.',
    icono: '♾️',
    orden: 38,
  },

  // Nuevos logros de reportes (hasta 200)
  {
    tipo: 'reportes_totales',
    valorObjetivo: 40,
    nombre: 'Centinela',
    descripcion: '40 reportes enviados. Vigilia absoluta.',
    icono: '🛎️',
    orden: 39,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 60,
    nombre: 'Observador Maestro',
    descripcion: '60 reportes realizados. Tu ojo crítico es invaluable.',
    icono: '🔍',
    orden: 40,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 80,
    nombre: 'Escudo de Datos',
    descripcion: '80 errores detectados y reportados. Eres protección pura.',
    icono: '🛡️',
    orden: 41,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 100,
    nombre: 'Protector del Sistema',
    descripcion: '100 reportes. Mantienes el sistema sano.',
    icono: '🧿',
    orden: 42,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 120,
    nombre: 'Ojo Divino',
    descripcion: '120 reportes totales. Exactitud sobrenatural.',
    icono: '🌙',
    orden: 43,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 150,
    nombre: 'Escuadrón de Calidad',
    descripcion: '150 reportes: lideras la integridad del sistema.',
    icono: '🛰️',
    orden: 44,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 200,
    nombre: 'Santo Guardián del Dato',
    descripcion: '200 reportes detectados. Perfección en vigilancia.',
    icono: '🕊️',
    orden: 45,
  },
]
