import type { NewLogro } from '@/db/schema'

/**
 * Configuración de logros del sistema
 * Define todos los logros disponibles con sus valores objetivo
 */
export const ACHIEVEMENTS_CONFIG: Omit<NewLogro, 'id' | 'creadoEn'>[] = [
  // Logros de validaciones totales (al menos 20)
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 10,
    nombre: 'Primeros Pasos',
    descripcion: 'Valida tus primeras 10 actas',
    icono: '🎯',
    orden: 1,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 20,
    nombre: 'En Marcha',
    descripcion: 'Valida 20 actas',
    icono: '🚀',
    orden: 2,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 50,
    nombre: 'Comprometido',
    descripcion: 'Valida 50 actas',
    icono: '⭐',
    orden: 3,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 100,
    nombre: 'Centurión',
    descripcion: 'Valida 100 actas',
    icono: '💯',
    orden: 4,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 200,
    nombre: 'Dedicado',
    descripcion: 'Valida 200 actas',
    icono: '🔥',
    orden: 5,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 300,
    nombre: 'Experto',
    descripcion: 'Valida 300 actas',
    icono: '🏆',
    orden: 6,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 400,
    nombre: 'Maestro',
    descripcion: 'Valida 400 actas',
    icono: '👑',
    orden: 7,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 500,
    nombre: 'Leyenda',
    descripcion: 'Valida 500 actas',
    icono: '🌟',
    orden: 8,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 600,
    nombre: 'Increíble',
    descripcion: 'Valida 600 actas',
    icono: '💎',
    orden: 9,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 700,
    nombre: 'Épico',
    descripcion: 'Valida 700 actas',
    icono: '⚡',
    orden: 10,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 800,
    nombre: 'Extraordinario',
    descripcion: 'Valida 800 actas',
    icono: '🎖️',
    orden: 11,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 900,
    nombre: 'Fenomenal',
    descripcion: 'Valida 900 actas',
    icono: '🏅',
    orden: 12,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 1000,
    nombre: 'Mil Validaciones',
    descripcion: 'Valida 1000 actas',
    icono: '🎊',
    orden: 13,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 1500,
    nombre: 'Super Estrella',
    descripcion: 'Valida 1500 actas',
    icono: '✨',
    orden: 14,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 2000,
    nombre: 'Campeón',
    descripcion: 'Valida 2000 actas',
    icono: '🥇',
    orden: 15,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 2500,
    nombre: 'Héroe',
    descripcion: 'Valida 2500 actas',
    icono: '🦸',
    orden: 16,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 3000,
    nombre: 'Ídolo',
    descripcion: 'Valida 3000 actas',
    icono: '🎭',
    orden: 17,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 4000,
    nombre: 'Mito',
    descripcion: 'Valida 4000 actas',
    icono: '🗿',
    orden: 18,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 5000,
    nombre: 'Inmortal',
    descripcion: 'Valida 5000 actas',
    icono: '⚔️',
    orden: 19,
  },
  {
    tipo: 'validaciones_totales',
    valorObjetivo: 10000,
    nombre: 'Dios del Voto',
    descripcion: 'Valida 10000 actas',
    icono: '👼',
    orden: 20,
  },

  // Logros de racha en sesión
  {
    tipo: 'racha_sesion',
    valorObjetivo: 10,
    nombre: 'Racha Inicial',
    descripcion: 'Valida 10 actas en una sola sesión',
    icono: '🔥',
    orden: 21,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 20,
    nombre: 'En Fuego',
    descripcion: 'Valida 20 actas en una sola sesión',
    icono: '🔥🔥',
    orden: 22,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 30,
    nombre: 'Racha Caliente',
    descripcion: 'Valida 30 actas en una sola sesión',
    icono: '🔥🔥🔥',
    orden: 23,
  },
  {
    tipo: 'racha_sesion',
    valorObjetivo: 50,
    nombre: 'Racha Épica',
    descripcion: 'Valida 50 actas en una sola sesión',
    icono: '🔥🔥🔥🔥',
    orden: 24,
  },

  // Logros de reportes
  {
    tipo: 'reportes_totales',
    valorObjetivo: 5,
    nombre: 'Vigilante',
    descripcion: 'Reporta 5 problemas',
    icono: '👁️',
    orden: 25,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 10,
    nombre: 'Protector',
    descripcion: 'Reporta 10 problemas',
    icono: '🛡️',
    orden: 26,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 20,
    nombre: 'Guardián',
    descripcion: 'Reporta 20 problemas',
    icono: '⚔️',
    orden: 27,
  },
  {
    tipo: 'reportes_totales',
    valorObjetivo: 25,
    nombre: 'Defensor',
    descripcion: 'Reporta 25 problemas',
    icono: '🦸',
    orden: 28,
  },
]
